# Generated by Django 5.1 on 2024-09-14 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LocationSearchStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sido', models.CharField(max_length=100)),
                ('sigungu', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'location_search_stage',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ERRealtimeInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hpid', models.CharField(max_length=50)),
                ('dutyName', models.CharField(max_length=255)),
                ('hvec', models.IntegerField(blank=True, null=True)),
                ('hvccc', models.IntegerField(blank=True, null=True)),
                ('hv2', models.IntegerField(blank=True, null=True)),
                ('hv3', models.IntegerField(blank=True, null=True)),
                ('hv6', models.IntegerField(blank=True, null=True)),
                ('hv34', models.IntegerField(blank=True, null=True)),
                ('hvctayn', models.CharField(blank=True, max_length=1, null=True)),
                ('hvmriayn', models.CharField(blank=True, max_length=1, null=True)),
                ('hvangioayn', models.CharField(blank=True, max_length=1, null=True)),
                ('hvventiayn', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'er_realtime_info',
            },
        ),
    ]
