# Generated by Django 5.1 on 2024-09-14 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('er_info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errealtimeinfo',
            name='hvangioayn',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='errealtimeinfo',
            name='hvctayn',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='errealtimeinfo',
            name='hvmriayn',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='errealtimeinfo',
            name='hvventiayn',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
